nodeLinker: node-modules

packageExtensions:
  '@remix-run/dev@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/express@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/node@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/serve@*':
    peerDependencies:
      react: '*'
      react-dom: '*'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
